package org.sainm.schemapilot.parser;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.sainm.schemapilot.model.DbObjectType;

class SqlObjectClassifierTest {

    private final SqlObjectClassifier classifier = new SqlObjectClassifier();

    @Test
    void recognizesCoreOracleObjectTypes() {
        assertThat(classifier.classify("create table users (id number)").objectType()).isEqualTo(DbObjectType.TABLE);
        assertThat(classifier.classify("create index ix_users on users(id)").objectType()).isEqualTo(DbObjectType.INDEX);
        assertThat(classifier.classify("create bitmap index ix_users_status on users(status)").objectType()).isEqualTo(DbObjectType.INDEX);
        assertThat(classifier.classify("create or replace view v_users as select * from users").objectType()).isEqualTo(DbObjectType.VIEW);
        assertThat(classifier.classify("create or replace force editionable view v_users as select * from users").objectType()).isEqualTo(DbObjectType.VIEW);
        assertThat(classifier.classify("create sequence users_seq").objectType()).isEqualTo(DbObjectType.SEQUENCE);
        assertThat(classifier.classify("create or replace trigger users_bi before insert on users begin null; end;").objectType()).isEqualTo(DbObjectType.TRIGGER);
        assertThat(classifier.classify("create or replace function f return number as begin return 1; end;").objectType()).isEqualTo(DbObjectType.FUNCTION);
        assertThat(classifier.classify("create or replace procedure p as begin null; end;").objectType()).isEqualTo(DbObjectType.PROCEDURE);
        assertThat(classifier.classify("create or replace package pkg as procedure p; end;").objectType()).isEqualTo(DbObjectType.PACKAGE);
        assertThat(classifier.classify("create or replace package body pkg as procedure p is begin null; end; end;").objectType()).isEqualTo(DbObjectType.PACKAGE_BODY);
    }

    @Test
    void extractsQuotedAndSchemaQualifiedNames() {
        ClassifiedSqlObject classified = classifier.classify("create table HR.\"User Account\" (id number)");

        assertThat(classified.schema()).isEqualTo("HR");
        assertThat(classified.name()).isEqualTo("User Account");
    }

    @Test
    void recognizesOracleTemporaryTables() {
        ClassifiedSqlObject globalTemporary = classifier.classify("create global temporary table temp_orders (id number)");
        ClassifiedSqlObject privateTemporary = classifier.classify("create private temporary table ora$ptt_users (id number)");

        assertThat(globalTemporary.objectType()).isEqualTo(DbObjectType.TABLE);
        assertThat(globalTemporary.name()).isEqualTo("temp_orders");
        assertThat(privateTemporary.objectType()).isEqualTo(DbObjectType.TABLE);
        assertThat(privateTemporary.name()).isEqualTo("ora$ptt_users");
    }

    @Test
    void recognizesObjectAfterLeadingComments() {
        ClassifiedSqlObject classified = classifier.classify("""
                -- generated by export tool;
                /* metadata: schema only; no rows */
                create table users (id number)
                """);

        assertThat(classified.objectType()).isEqualTo(DbObjectType.TABLE);
        assertThat(classified.name()).isEqualTo("users");
    }
}
