package org.sainm.schemapilot.parser;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class SqlStatementSplitterTest {

    private final SqlStatementSplitter splitter = new SqlStatementSplitter();

    @Test
    void splitsDdlAndSlashTerminatedPlsqlBlocks() {
        String sql = """
                create table users (id number(10,0));

                create or replace trigger users_bi
                before insert on users
                for each row
                begin
                  :new.created_at := sysdate;
                end;
                /

                create sequence users_seq;
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        "create table users (id number(10,0));",
                        """
                                create or replace trigger users_bi
                                before insert on users
                                for each row
                                begin
                                  :new.created_at := sysdate;
                                end;
                                /""",
                        "create sequence users_seq;");
    }

    @Test
    void splitsMultipleSqlStatementsOnOneLine() {
        assertThat(splitter.split("create table users (id number); create view v_users as select * from users;"))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        "create table users (id number);",
                        "create view v_users as select * from users;");
    }

    @Test
    void preservesCompactPlsqlBlockAfterFirstSemicolon() {
        String sql = """
                create or replace function f return number is begin return 1; end;
                /
                create table t (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        "create or replace function f return number is begin return 1; end;\n/",
                        "create table t (id number);");
    }

    @Test
    void preservesPlsqlBlockAfterLeadingComments() {
        String sql = """
                -- generated by export tool
                /* package metadata */
                create or replace function f return number is begin return 1; end;
                /
                create table t (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        "-- generated by export tool\n/* package metadata */\ncreate or replace function f return number is begin return 1; end;\n/",
                        "create table t (id number);");
    }

    @Test
    void preservesEditionablePlsqlBlocks() {
        String sql = """
                create or replace editionable function f return number is begin return 1; end;
                /
                create or replace noneditionable procedure p is begin null; end;
                /
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        "create or replace editionable function f return number is begin return 1; end;\n/",
                        "create or replace noneditionable procedure p is begin null; end;\n/");
    }

    @Test
    void ignoresSemicolonsInsideComments() {
        String sql = """
                -- generated by export tool;
                /* metadata: schema only; no rows */
                create table users (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly("-- generated by export tool;\n/* metadata: schema only; no rows */\ncreate table users (id number);");
    }

    @Test
    void ignoresSemicolonsInsideOracleQQuotedLiterals() {
        String sql = """
                create table notes (body varchar2(100) default q'[Bob's note; keep]');
                create table users (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        "create table notes (body varchar2(100) default q'[Bob's note; keep]');",
                        "create table users (id number);");
    }

    @Test
    void ignoresSemicolonsInsideMultilineOracleQQuotedLiterals() {
        String sql = """
                create table notes (
                  body varchar2(100) default q'[Bob's note;
                still; keep]'
                );
                create table users (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        """
                                create table notes (
                                  body varchar2(100) default q'[Bob's note;
                                still; keep]'
                                );""",
                        "create table users (id number);");
    }

    @Test
    void ignoresSemicolonsInsideMultilineStringLiterals() {
        String sql = """
                create table notes (
                  body varchar2(100) default 'line1
                line2');
                create table users (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        """
                                create table notes (
                                  body varchar2(100) default 'line1
                                line2');""",
                        "create table users (id number);");
    }

    @Test
    void ignoresSlashTerminatorInsidePlsqlQQuotedLiterals() {
        String sql = """
                create or replace function f return varchar2 is
                begin
                  return q'[
                /
                ]';
                end;
                /
                create table t (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        """
                                create or replace function f return varchar2 is
                                begin
                                  return q'[
                                /
                                ]';
                                end;
                                /""",
                        "create table t (id number);");
    }

    @Test
    void ignoresApostrophesInsidePlsqlCommentsWhenFindingSlashTerminator() {
        String sql = """
                create or replace function f return number is
                begin
                  -- don't treat this comment as a string literal
                  return 1;
                end;
                /
                create table t (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        """
                                create or replace function f return number is
                                begin
                                  -- don't treat this comment as a string literal
                                  return 1;
                                end;
                                /""",
                        "create table t (id number);");
    }

    @Test
    void ignoresSlashTerminatorInsidePlsqlMultilineStringLiterals() {
        String sql = """
                create or replace function f return varchar2 is
                begin
                  return '
                /
                ';
                end;
                /
                create table t (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        """
                                create or replace function f return varchar2 is
                                begin
                                  return '
                                /
                                ';
                                end;
                                /""",
                        "create table t (id number);");
    }

    @Test
    void preservesOpenStringWhenFirstLineStartsPlsqlBlock() {
        String sql = """
                create or replace function f return varchar2 is begin return '
                /
                ';
                end;
                /
                create table t (id number);
                """;

        assertThat(splitter.split(sql))
                .extracting(ParsedStatement::text)
                .containsExactly(
                        """
                                create or replace function f return varchar2 is begin return '
                                /
                                ';
                                end;
                                /""",
                        "create table t (id number);");
    }
}
